//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BengansBowlingApplikation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookTable
    {
        public int BookNumber { get; set; }
        public int UserNumber { get; set; }
        public int ContestNumber { get; set; }
    
        public virtual ContestTable ContestTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
