//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BengansBowlingApplikation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BengansBowlingEntities1 : DbContext
    {
        public BengansBowlingEntities1()
            : base("name=BengansBowlingEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookTable> BookTable { get; set; }
        public virtual DbSet<ContestTable> ContestTable { get; set; }
        public virtual DbSet<UserTable> UserTable { get; set; }
    }
}
